export const TRANSLATE = {
  ru: {
    welcome: {
      title: 'Добро пожаловать на страницу',
      creators: 'разработана студентами RS School - Angular Q1 2022',
      teamHeader: 'Наша команда',
    },
    header: {
      create: 'Создать доску',
      hello: 'Привет,',
      edit: 'Редактировать',
      logout: 'Выйти',
    },
    login: {
      title: 'Вход',
      login: 'Логин',
      pass: 'Пароль',
      msg: 'Для входа все поля должны быть заполненны.',
      warMsgLen1: 'Минимальная длина пароля ',
      warMsgLen2: ' символа',
      warMsgNotFound: 'Пользователь с таким логином и паролем не найден',
      warMsgRequire: 'Поле не может быть пустым',
      btn: 'Войти',
    },
    profile: {
      titleReg: 'Создать профиль',
      titleEdit: 'Изменить профиль',
      login: 'Логин',
      pass: 'Пароль',
      passConf: 'Подтверждение пароля',
      msg: 'Все поля должны быть заполненны.',
      msgReg: 'Пользователь успешно зарегистрирован',
      msgEdit: 'Профиль успешно обновлен',
      warMsgLen1: 'Минимальная длина пароля ',
      warMsgLen2: ' символа',
      warMsgNotFound: 'Пользователь с таким логином и паролем не найден',
      warMsgRequire: 'Поле не может быть пустым',
      warMsgNotEqual: 'Пароли не совпадают.',
      warMsgRand: 'Что-то пошло не так, попробуйте еще раз',
      warMsgCopy: 'Пользователь с таким логином уже зарегистрирован',
      btnReg: 'Зарегистрировать',
      btnEdit: 'Изменить',
      btnDelete: 'Удалить профиль',
      name: 'Имя',}
    modal: {
      ok: 'Ок',
      cancel: 'Отмена',
      empty: 'Поле не должно быть пустым',
      action: 'Подтвердите действие на странице',
    },
    createBoard: {
      task: 'Введите заголовок доски',
      title: 'Моя новая доска',
      description: 'Описание доски',
    },
    boards: {
      title: 'Мои доски',
    },
  },
  en: {
    welcome: {
      title: 'Welcome to',
      creators: 'by students of RS School - Angular Q1 2022',
      teamHeader: 'Our team',
    },
    header: {
      create: 'Create new board',
      hello: 'Hello,',
      edit: 'Edit profile',
      logout: 'Logout',
    },
    login: {
      title: 'SignIn',
      login: 'login',
      pass: 'Password',
      msg: 'All fields must be filled in signin.',
      warMsgLen1: 'Minimum password length ',
      warMsgLen2: ' letters.',
      warMsgNotFound: 'No user found with this username and password',
      warMsgRequire: 'Field cannot be empty',
      btn: 'Submit',
    },
    profile: {
      titleReg: 'Create an account',
      titleEdit: 'Edit Profil',
      login: 'login',
      pass: 'Password',
      passConf: 'Password confirmation',
      msg: 'All fields must be filled.',
      msgReg: 'User successfully registered',
      msgEdit: 'Profile updated successfully',
      warMsgLen1: 'Minimum password length ',
      warMsgLen2: ' letters.',
      warMsgNotFound: 'No user found with this username and password',
      warMsgRequire: 'Field cannot be empty',
      warMsgNotEqual: 'Passwords do not match',
      warMsgRand: 'Something went wrong, please try again',
      warMsgCopy: 'User with this login is already registered',
      btnReg: 'Create',
      btnEdit: 'Edit',
      btnDelete: 'Delete profile',
      name: 'Name',}
      
    modal: {
      ok: 'Ok',
      cancel: 'Cancel',
      empty: 'This field should not be empty',
      action: 'Confirm action',
    },
    createBoard: {
      task: 'Enter a new board title',
      title: 'New Board',
      description: 'Description of the board',
    },
    boards: {
      title: 'My boards',
    },
  },
};
