export const TRANSLATE = {
  ru: {
    welcome: {
      title: 'Добро пожаловать на страницу',
      creators: 'разработана студентами RS School - Angular Q1 2022',
      teamHeader: 'Наша команда',
      develop: 'Разработчик',
      lid: 'Тимлид, разработчик',
      vlad: 'Общая структура проекта, хэдер и футер, страница доски, drag and drop на странице доски',
      elina:
        'Сервисы для работы с сервером, страница со списком досок, приветственная страница, модальные окна',
      sasha:
        'Страница логина и регистрации, редактирование пользователя, поиск задач, обработка сделанной задачи',
    },
    header: {
      create: 'Создать доску',
      hello: 'Привет,',
      edit: 'Редактировать',
      logout: 'Выйти',
    },
    login: {
      title: 'Вход',
      login: 'Логин',
      pass: 'Пароль',
      msg: 'Для входа все поля должны быть заполненны.',
      warMsgLen1: 'Минимальная длина пароля ',
      warMsgLen2: ' символа',
      warMsgNotFound: 'Пользователь с таким логином и паролем не найден',
      warMsgRequire: 'Поле не может быть пустым',
      btn: 'Войти',
    },
    profile: {
      titleReg: 'Создать профиль',
      titleEdit: 'Изменить профиль',
      login: 'Логин',
      pass: 'Пароль',
      passConf: 'Подтверждение пароля',
      msg: 'Все поля должны быть заполненны.',
      msgReg: 'Пользователь успешно зарегистрирован',
      msgEdit: 'Профиль успешно обновлен',
      warMsgLen1: 'Минимальная длина пароля ',
      warMsgLen2: ' символа',
      warMsgNotFound: 'Пользователь с таким логином и паролем не найден',
      warMsgRequire: 'Поле не может быть пустым',
      warMsgNotEqual: 'Пароли не совпадают.',
      warMsgRand: 'Что-то пошло не так, попробуйте еще раз',
      warMsgCopy: 'Пользователь с таким логином уже зарегистрирован',
      btnReg: 'Зарегистрировать',
      btnEdit: 'Изменить',
      btnDelete: 'Удалить профиль',
      name: 'Имя',
    },
    modal: {
      ok: 'Ок',
      cancel: 'Отмена',
      empty: 'Поле не должно быть пустым',
      action: 'Подтвердите действие на странице',
      error: 'Что-то пошло не так, попробуйте ещё раз',
    },
    createBoard: {
      task: 'Введите заголовок доски',
      title: 'Моя новая доска',
      description: 'Описание доски',
    },
    boards: {
      title: 'Мои доски',
    },
    search: {
      category: 'Категория',
      search: 'Поиск',
      title: 'название',
      description: 'описание',
      name: 'имя',
      valid: 'Введите более 2 символов',
      notFound: 'По вашему запросу ничего не найдено, измените критерии поиска',
    },
    board: {
      back: 'назад',
      add: 'новая колонка',
      createTask: 'новая задача',
      removeCol: 'удалить колонку',
      deleteTask: 'удалить задачу',
      editTask: 'редактировать задачу',
      done: 'завершить задачу',
      unDone: 'вернуть в работу',
      modalNewCol: {
        task: 'Введите заголовок колонки',
        title: 'Новая колонка',
      },
      modalNewTask: {
        task: 'Введите заголовок задачи',
        title: 'Новая задача',
        description: 'Описание задачи',
      },
    },
  },
  en: {
    welcome: {
      title: 'Welcome to',
      creators: 'by students of RS School - Angular Q1 2022',
      teamHeader: 'Our team',
      develop: 'Developer',
      lid: 'TeamLead, developer',
      vlad: 'General project structure, header and footer, board page, drag and drop on the board page',
      elina: 'Server Services, Board List Page, Welcome Page, Modals',
      sasha:
        'Login and registration page, edit user, search tasks, process done task',
    },
    header: {
      create: 'Create new board',
      hello: 'Hello,',
      edit: 'Edit profile',
      logout: 'Logout',
    },
    login: {
      title: 'SignIn',
      login: 'login',
      pass: 'Password',
      msg: 'All fields must be filled in signin.',
      warMsgLen1: 'Minimum password length ',
      warMsgLen2: ' letters.',
      warMsgNotFound: 'No user found with this username and password',
      warMsgRequire: 'Field cannot be empty',
      btn: 'Submit',
    },
    profile: {
      titleReg: 'Create an account',
      titleEdit: 'Edit Profil',
      login: 'login',
      pass: 'Password',
      passConf: 'Password confirmation',
      msg: 'All fields must be filled.',
      msgReg: 'User successfully registered',
      msgEdit: 'Profile updated successfully',
      warMsgLen1: 'Minimum password length ',
      warMsgLen2: ' letters.',
      warMsgNotFound: 'No user found with this username and password',
      warMsgRequire: 'Field cannot be empty',
      warMsgNotEqual: 'Passwords do not match',
      warMsgRand: 'Something went wrong, please try again',
      warMsgCopy: 'User with this login is already registered',
      btnReg: 'Create',
      btnEdit: 'Edit',
      btnDelete: 'Delete profile',
      name: 'Name',
    },

    modal: {
      ok: 'Ok',
      cancel: 'Cancel',
      empty: 'This field should not be empty',
      action: 'Confirm action',
      error: 'Something wrong, please try again',
    },
    createBoard: {
      task: 'Enter a new board title',
      title: 'New Board',
      description: 'Description of the board',
    },
    boards: {
      title: 'My boards',
    },
    search: {
      category: 'Category',
      search: 'Search',
      title: 'title',
      description: 'descripton',
      name: 'name',
      valid: 'Please enter more than 2 characters',
      notFound: 'No results were found for your search, please change your search criteria',
    },
    board: {
      back: 'back',
      add: 'add column',
      createTask: 'create task',
      removeCol: 'remove column',
      deleteTask: 'delete task',
      editTask: 'edit task',
      done: 'done task',
      unDone: 'undo done',
      modalNewCol: {
        task: 'Enter new column title',
        title: 'New Column',
      },
      modalNewTask: {
        task: 'Enter new task title',
        title: 'New Task',
        description: 'Description of the task',
      },
    },
  },
};
